#!/bin/bash

if [[ $1 = "on" ]]; then
    doas systemctl start bluetooth && bluetoothctl power on && bluetoothctl
  elif [[ $1 = "off" ]]; then
    doas systemctl stop bluetooth
  elif [[ $1 = "ctl" ]]; then
    bluetoothctl	  
  else
    printf "Error: Wrong/Missing argument.\n\nUsage: bt [arguments]\nArguments:\n   on:       Turn On bluetooth service and Power.\n  off:       Turn Off bluetooth service and Power.\n  ctl:       bluetoothctl mode.\n"
fi 
