#!/bin/bash

if [[ $1 = "on" ]]; then
    doas systemctl start dnscrypt-proxy.service 
    doas sh -c 'printf "resolv_conf=/etc/resolv.conf \nname_servers=127.0.0.1\n" > /etc/resolvconf.conf'
    doas resolvconf -u
  elif [[ $1 = "off" ]]; then
    doas sh -c 'printf "resolv_conf=/etc/resolv.conf \n#name_servers=127.0.0.1\n" > /etc/resolvconf.conf'
    doas systemctl stop dnscrypt-proxy.service
    doas resolvconf -u    
  else
    printf "Error: Wrong/Missing argument.\n\nUsage: dns [arguments]\nArguments:\n   on:       Turn On DNS service.\n  off:       Turn Off DNS service.\n"
fi 
