#!/bin/bash

if [[ $1 = "on" ]]; 
  then
    xinput enable 14
  elif [[ $1 = "off" ]]; 
  then
    xinput disable 14
  elif [[ $1 = "tapon" ]]; 
  then
    xinput -set-prop 14 333 1    
  elif [[ $1 = "tapoff" ]]; 
  then
    xinput -set-prop 14 333 0
  else
    printf "Error: Wrong/Missing argument.\n\nUsage: tcpd [arguments]\nArguments:\n  on      :       Enable Touchpad.\n  off     :       Disable Touchpad.\n  tap on  :       Enable Touchpad tapping mode.\n  tap off :       Disable Touchpad tapping mode.\n"
fi 